import { useAppStore } from '../store/useAppStore';
import { secureStorage } from '../lib/encryption';
import { retrieveRelevantContext, generateEmbedding } from '../lib/rag';
import { Story, IntakeData, WorldBlueprint, Chapter, StoryArc, StoryMemory, StoryWorld, GeneratedImage } from '../types';
import { storyStorage } from '../lib/storage';
import { awardQi } from '../lib/qi';

export const extractJsonBlocks = (rawStr: string): any[] => {
  // 1. Try arrays wrapped in markdown or raw
  try {
    const arrayMatch = rawStr.match(/\[\s*\{[\s\S]*\}\s*\]/);
    if (arrayMatch) {
       const parsed = JSON.parse(arrayMatch[0]);
       if (Array.isArray(parsed) && parsed.length > 0 && (typeof parsed[0].text === 'string' || typeof parsed[0].content === 'string')) {
          return parsed.map(b => ({ ...b, text: b.text || b.content }));
       }
    }
  } catch(e) {}

  // 2. Strict NDJSON line-by-line fallback
  let blocks: any[] = [];
  const lines = rawStr.split('\n');
  for (let l of lines) {
    const trimmed = l.trim();
    if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
      try {
        const obj = JSON.parse(trimmed);
        if (obj && (typeof obj.text === 'string' || typeof obj.content === 'string')) {
          blocks.push({ ...obj, text: obj.text || obj.content });
        }
      } catch (e) {}
    }
  }
  if (blocks.length > 0) return blocks;

  // 3. Balanced brace extraction (Handles pretty-printed, drift, trailing commas gracefully-ish but JSON.parse must succeed)
  let braceBlocks: any[] = [];
  let depth = 0;
  let currentBlock = "";
  let inString = false;
  let escapeNext = false;
  
  for (let i = 0; i < rawStr.length; i++) {
    const char = rawStr[i];
    if (escapeNext) {
      if (depth > 0) currentBlock += char;
      escapeNext = false;
      continue;
    }
    if (char === '\\') {
      escapeNext = true;
      if (depth > 0) currentBlock += char;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      if (depth > 0) currentBlock += char;
      continue;
    }
    if (!inString) {
      if (char === '{') {
        if (depth === 0) currentBlock = '{';
        else currentBlock += char;
        depth++;
      } else if (char === '}') {
        depth--;
        currentBlock += char;
        if (depth === 0) {
          try {
            // Fix trailing commas often generated by LLMs before parsing
            let fixStr = currentBlock.replace(/,\s*([\]}])/g, '$1');
            const obj = JSON.parse(fixStr);
            if (obj && (typeof obj.text === 'string' || typeof obj.content === 'string')) {
              braceBlocks.push({ ...obj, text: obj.text || obj.content });
            }
          } catch(e) {}
        }
      } else if (depth > 0) {
         currentBlock += char;
      }
    } else {
      if (depth > 0) currentBlock += char;
    }
  }
  return braceBlocks;
};

export const extractJsonMeta = (rawStr: string): any => {
  let cleanJson = rawStr.replace(/```json/gi, '').replace(/```/g, '').trim();
  cleanJson = cleanJson.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  
  try { return JSON.parse(cleanJson); } catch (e) {}

  // Find longest balanced object
  let depth = 0;
  let currentBlock = "";
  let inString = false;
  let escapeNext = false;
  let longestObject: any = null;
  let longestLength = 0;
  
  for (let i = 0; i < cleanJson.length; i++) {
    const char = cleanJson[i];
    if (escapeNext) {
      if (depth > 0) currentBlock += char;
      escapeNext = false;
      continue;
    }
    if (char === '\\') {
      escapeNext = true;
      if (depth > 0) currentBlock += char;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      if (depth > 0) currentBlock += char;
      continue;
    }
    if (!inString) {
      if (char === '{') {
        if (depth === 0) currentBlock = '{';
        else currentBlock += char;
        depth++;
      } else if (char === '}') {
        depth--;
        currentBlock += char;
        if (depth === 0) {
          try {
            let fixStr = currentBlock.replace(/,\s*([\]}])/g, '$1');
            const obj = JSON.parse(fixStr);
            if (currentBlock.length > longestLength) {
              longestLength = currentBlock.length;
              longestObject = obj;
            }
          } catch(e) {}
        }
      } else if (depth > 0) {
         currentBlock += char;
      }
    } else {
      if (depth > 0) currentBlock += char;
    }
  }
  
  return longestObject || {};
};

function getLevenshteinDistance(v1: string, v2: string): number {
  if (!v1 || !v2) return Math.max(v1?.length || 0, v2?.length || 0);
  if (v1 === v2) return 0;
  const matrix = [];
  for (let i = 0; i <= v2.length; i++) {
    matrix[i] = [i];
  }
  for (let j = 0; j <= v1.length; j++) {
    matrix[0][j] = j;
  }
  for (let i = 1; i <= v2.length; i++) {
    for (let j = 1; j <= v1.length; j++) {
      if (v2.charAt(i - 1) === v1.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1];
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1,
          Math.min(matrix[i][j - 1] + 1, matrix[i - 1][j] + 1)
        );
      }
    }
  }
  return matrix[v2.length][v1.length];
}

function runMemoryLinter(
  prevMemory: StoryMemory,
  nextMemory: StoryMemory,
  chapterText: string
): string[] {
  const warnings: string[] = [];

  // 1. Dead character referenced in new text
  if (prevMemory.characters) {
    prevMemory.characters.forEach((char) => {
      if (char.status?.toLowerCase() === 'deceased') {
        const regex = new RegExp(`\\b${char.name}\\b`, 'i');
        if (regex.test(chapterText)) {
          warnings.push(`Deceased character "${char.name}" was referenced in the new text. Verify this was a flashback or memory.`);
        }
      }
    });
  }

  // 2. Duplicateish Names (Levenshtein) in updated roster
  if (nextMemory.characters) {
    for (let i = 0; i < nextMemory.characters.length; i++) {
      for (let j = i + 1; j < nextMemory.characters.length; j++) {
        const name1 = nextMemory.characters[i].name;
        const name2 = nextMemory.characters[j].name;
        if (name1 && name2 && name1.toLowerCase() !== name2.toLowerCase()) {
          const distance = getLevenshteinDistance(name1.toLowerCase(), name2.toLowerCase());
          if (distance > 0 && distance <= 2 && name1.length > 4 && name2.length > 4) {
             warnings.push(`Potential duplicate character names: "${name1}" and "${name2}". Check roster.`);
          }
        }
      }
    }
  }

  // 3. Power stage skipping
  if (prevMemory.currentPowerStage !== nextMemory.currentPowerStage) {
     const prevStage = prevMemory.currentPowerStage || 'None';
     warnings.push(`Power stage updated from "${prevStage}" to "${nextMemory.currentPowerStage}". Verify no ranks were skipped.`);
  }

  // 4. Returning Dead/Resolved threads
  if (nextMemory.unresolvedPlotThreads && prevMemory.resolvedPlotThreads) {
    for (const thread of nextMemory.unresolvedPlotThreads) {
      const threadStr = typeof thread === 'string' ? thread : thread.description;
      if (prevMemory.resolvedPlotThreads.some(r => {
        const rStr = typeof r === 'string' ? r : r.description;
        return rStr.toLowerCase() === threadStr.toLowerCase();
      })) {
        warnings.push(`Plot thread "${threadStr}" was previously resolved but is now marked unresolved.`);
      }
    }
  }

  return warnings;
}

export const useStoryEngine = () => {
  const store = useAppStore();

  const getApiHeaders = async () => {
    const apiHeaders: Record<string, string> = { 'Content-Type': 'application/json' };
    const gemini = await secureStorage.getItem('@seihouse/api-key-gemini');
    const openrouter = await secureStorage.getItem('@seihouse/api-key-openrouter');
    const ollama = await secureStorage.getItem('@seihouse/api-key-ollama-host');
    if (gemini) apiHeaders['x-gemini-key'] = gemini;
    if (openrouter) apiHeaders['x-openrouter-key'] = openrouter;
    if (ollama) apiHeaders['x-ollama-host'] = ollama;
    return apiHeaders;
  };

  const handleGenerateBlueprint = async (intake: IntakeData): Promise<WorldBlueprint> => {
    store.setGenerationPhase('blueprint');
    store.setActiveAgentId('versa');
    store.setIsGenerating(true);
    store.setAppError(null);
    try {
      const apiHeaders = await getApiHeaders();
      const response = await fetch('/api/generate-blueprint', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({ intake, routingConfig: store.routingConfig.storyMaker })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Blueprint generation failed: ${response.status}`);
      }
      return await response.json();
    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Failed to generate world blueprint.");
      throw err;
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setActiveAgentId(null);
    }
  };

  const handleStartStory = async (intake: IntakeData, blueprint: WorldBlueprint, chapterCount: number) => {
    store.setGenerationPhase('initial-arc');
    store.setActiveAgentId('versa');
    store.setIsGenerating(true);
    store.setAppError(null);

    try {
      const apiHeaders = await getApiHeaders();
      const response = await fetch('/api/generate-initial-arc', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({ intake, blueprint, chapterCount, routingConfig: store.routingConfig.storyMaker })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Server bounds ruptured with status: ${response.status}`);
      }

      const responseData = await response.json();

      const formattedChapters: Chapter[] = responseData.chapters.map((ch: any) => ({
        number: ch.number,
        title: ch.title,
        premise: ch.premise,
        status: 'unread'
      }));

      const newStory: Story = {
        id: `story-${Date.now()}`,
        title: responseData.title || blueprint.title || 'The Ascension Chronicles',
        genre: intake.genrePath || 'Xianxia',
        mcName: intake.mcName || 'Unknown',
        customPremise: intake.corePremise || blueprint.logline || '',
        intake: intake,
        blueprint: blueprint,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        currentChapterNumber: 1,
        memory: {
          powerSystem: responseData.powerSystem || blueprint.powerSystemOutline,
          currentPowerStage: responseData.currentPowerStage || 'Novice stage',
          worldRules: responseData.worldRules || ['Survival of the fittest'],
          characters: responseData.characters?.map((c: any) => ({
            id: `char-${Math.random().toString(36).substr(2, 9)}`,
            ...c
          })) || [],
          unresolvedPlotThreads: responseData.unresolvedPlotThreads || [],
          resolvedPlotThreads: []
        },
        arcs: [
          {
            title: responseData.title || 'Volume I Genesis',
            chapters: formattedChapters,
            isCompleted: false
          }
        ]
      };

      const updated = [newStory, ...store.stories];
      await store.saveStories(updated);
      store.setActiveStoryId(newStory.id);
      store.setSelectedChapterNum(1);
      store.setCurrentScreen('detail');
      awardQi('world_created');
    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Failed to align celestial gates.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setActiveAgentId(null);
    }
  };

  const handleGenerateChapter = async (chapterNumber: number) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    store.setGenerationPhase('chapter');
    store.setIsGenerating(true);
    store.setAppError(null);

    const selectedArcIndex = activeStory.arcs.findIndex(arc => arc.chapters.some(c => c.number === chapterNumber));
    if (selectedArcIndex === -1) return;

    const currentArc = activeStory.arcs[selectedArcIndex];
    const targetChapter = currentArc.chapters.find(c => c.number === chapterNumber);
    if (!targetChapter) return;

    try {
      store.setActiveAgentId('scout');
      const apiHeaders = await getApiHeaders();

      const pastSummaries = await retrieveRelevantContext(
        targetChapter.premise || activeStory.customPremise,
        chapterNumber,
        activeStory,
        apiHeaders,
        5
      );

      store.setActiveAgentId('versa');
      const response = await fetch('/api/generate-chapter-stream', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({
          mcName: activeStory.mcName,
          genre: activeStory.genre,
          customPremise: activeStory.customPremise,
          memory: activeStory.memory,
          pastSummaries,
          currentChapter: {
            number: targetChapter.number,
            title: targetChapter.title,
            premise: targetChapter.premise
          },
          routingConfig: store.routingConfig.storyMaker
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Meridian clash in chapter generation. Status: ${response.status}`);
      }

      if (!response.body) throw new Error("No streaming body available.");

      const reader = response.body.getReader();
      const decoder = new TextDecoder("utf-8");
      let accumulatedRaw = "";
      let buffer = "";

      const textHeader = "---CHAPTER_BLOCKS---";

      while(true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        
        let lines = buffer.split('\n');
        buffer = lines.pop() || "";
        
        for (const line of lines) {
          if (line.startsWith('data: ') && line !== 'data: [DONE]') {
            try {
              const parsed = JSON.parse(line.substring(6));
              if (parsed.error) throw new Error(parsed.error);
              if (parsed.chunk) {
                accumulatedRaw += parsed.chunk;
                
                let currentChapterText = "";
                let blocksData: any[] = [];
                let rawBlocksStr = accumulatedRaw;

                if (accumulatedRaw.includes(textHeader)) {
                  const startIndex = accumulatedRaw.indexOf(textHeader) + textHeader.length;
                  rawBlocksStr = accumulatedRaw.substring(startIndex).trim();
                }

                blocksData = extractJsonBlocks(rawBlocksStr);
                
                if (blocksData.length > 0) {
                   currentChapterText = blocksData.map(b => b.text).join('\\n\\n');
                } else {
                   currentChapterText = rawBlocksStr.replace(/\`\`\`json/gi, '').replace(/\`\`\`/g, '').trim();
                }

                if (!currentChapterText) {
                   currentChapterText = accumulatedRaw;
                }

                store.setStreamingChapter({
                  number: chapterNumber,
                  content: currentChapterText || "Condensing celestial aura...",
                  blocks: blocksData.length > 0 ? blocksData : undefined
                });
              }
            } catch (e: any) {
              if (e.message && e.message !== "Unexpected end of JSON input") {
                console.error("Stream parse error:", e);
              }
            }
          }
        }
      }

      let data: any = { chapterText: "", blocks: [], summary: "An ethereal mist obscures the historical records.", statsChangeMessage: "None", memoryUpdates: {} };
      
      let rawBlocksStr = accumulatedRaw;

      if (accumulatedRaw.includes(textHeader)) {
        const startIndex = accumulatedRaw.indexOf(textHeader) + textHeader.length;
        rawBlocksStr = accumulatedRaw.substring(startIndex).trim();
      }

      const parsedBlocks = extractJsonBlocks(rawBlocksStr);
      data.blocks = parsedBlocks;
      
      if (parsedBlocks.length > 0) {
        data.chapterText = parsedBlocks.map((b: any) => b.text).join('\\n\\n');
      } else {
        data.chapterText = rawBlocksStr.replace(/\`\`\`json/gi, '').replace(/\`\`\`/g, '').trim();
      }
      
      if (!data.chapterText) {
        data.chapterText = accumulatedRaw;
      }

      // Perform extraction step
      store.setStreamingChapter({
         number: chapterNumber,
         content: data.chapterText,
         blocks: data.blocks
      });

      const extractResponse = await fetch('/api/extract-chapter-metadata', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({
          chapterNumber: targetChapter.number,
          title: targetChapter.title,
          chapterText: rawBlocksStr,
          routingConfig: store.routingConfig.storyMaker
        })
      });

      if (!extractResponse.ok) {
         console.warn("Failed to extract chapter metadata explicitly. Setting defaults.");
      } else {
         const extractedData = await extractResponse.json();
         data = { ...data, ...extractedData };
      }

      let newChapterEmbedding;
      if (data.summary) {
        newChapterEmbedding = await generateEmbedding(data.summary, apiHeaders);
      }

      const freshStories = await storyStorage.getStories();
      const updatedStories = freshStories.map((s: Story) => {
        if (s.id !== activeStory.id) return s;

        const cloned = { ...s };
        
        cloned.arcs = cloned.arcs.map((arc, aIdx) => {
          if (aIdx !== selectedArcIndex) return arc;
          return {
            ...arc,
            summary: data.arcSummary || arc.summary,
            chapters: arc.chapters.map(ch => {
              if (ch.number !== chapterNumber) return ch;
              return {
                ...ch,
                _isNewContent: true,
                generatedContent: data.chapterText,
                blocks: data.blocks,
                summary: data.summary,
                embedding: newChapterEmbedding,
                statsChangeMessage: data.statsChangeMessage !== 'None' ? data.statsChangeMessage : undefined,
                cuePayload: data.cuePayload,
                status: 'read' as const
              };
            })
          };
        });

        const isArcFinished = cloned.arcs[selectedArcIndex].chapters.every(ch => ch.hasContent || !!ch.generatedContent);
        if (isArcFinished) {
          cloned.arcs[selectedArcIndex].isCompleted = true;
        }

        const memoryUpdates = data.memoryUpdates;
        if (memoryUpdates) {
          const nextMemory: StoryMemory = { ...cloned.memory };
          
          if (memoryUpdates.currentPowerStage) {
            nextMemory.currentPowerStage = memoryUpdates.currentPowerStage;
          }

          if (memoryUpdates.newCharacters && memoryUpdates.newCharacters.length > 0) {
            const added = memoryUpdates.newCharacters.map((c: any) => ({
              id: `char-${Math.random().toString(36).substr(2, 9)}`,
              name: c.name,
              role: c.role || 'Neutral figure',
              description: c.description || '',
              relationshipToMC: c.relationshipToMC || 'Neutral',
              status: c.status || 'alive',
              powerLevel: c.powerLevel || undefined,
              abilities: c.abilities || undefined,
              faction: c.faction || undefined,
              relevanceState: c.relevanceState || 'active',
              currentRelevance: c.currentRelevance || undefined,
              toneMemory: c.toneMemory || undefined,
              firstAppeared: c.firstAppeared || chapterNumber,
              lastMajorInvolvement: c.lastMajorInvolvement || chapterNumber
            }));
            nextMemory.characters = [...(nextMemory.characters || []), ...added];
          }

          if (memoryUpdates.characterStatusUpdates && memoryUpdates.characterStatusUpdates.length > 0) {
            nextMemory.characters = (nextMemory.characters || []).map(char => {
              const rule = memoryUpdates.characterStatusUpdates.find((u: any) => u.name?.toLowerCase() === char.name?.toLowerCase());
              if (rule) {
                const nextAbilities = char.abilities || [];
                const mergedAbilities = rule.newAbilities 
                  ? Array.from(new Set([...nextAbilities, ...rule.newAbilities]))
                  : nextAbilities;
                
                let newDesc = char.description;
                if (rule.descriptionAppend) {
                  newDesc = newDesc ? `${newDesc} ${rule.descriptionAppend}` : rule.descriptionAppend;
                }

                const powerLevelChanged = rule.newPowerLevel && rule.newPowerLevel !== char.powerLevel;
                const statusChanged = rule.newStatus && rule.newStatus !== char.status;
                const evolutionReady = powerLevelChanged || statusChanged || char.evolutionReady || false;
                const evolutionReason = powerLevelChanged ? "Breakthrough in Power Level" : (statusChanged ? "Major Status Change" : char.evolutionReason);

                return {
                  ...char,
                  description: newDesc,
                  status: rule.newStatus || char.status,
                  relationshipToMC: rule.newRelationship || char.relationshipToMC,
                  powerLevel: rule.newPowerLevel || char.powerLevel,
                  abilities: mergedAbilities.length > 0 ? mergedAbilities : undefined,
                  relevanceState: rule.relevanceState || char.relevanceState,
                  currentRelevance: rule.currentRelevance || char.currentRelevance,
                  toneMemory: rule.toneMemory || char.toneMemory,
                  lastMajorInvolvement: rule.lastMajorInvolvement || char.lastMajorInvolvement,
                  evolutionReady: evolutionReady,
                  evolutionReason: evolutionReason,
                  availableVisualUpdate: evolutionReady
                };
              }
              return char;
            });
          }

          if (memoryUpdates.factionUpdates && memoryUpdates.factionUpdates.length > 0) {
            nextMemory.factions = (nextMemory.factions || []).map(f => {
              const rule = memoryUpdates.factionUpdates.find((u: any) => u.name?.toLowerCase() === f.name?.toLowerCase());
              if (rule) {
                let newDesc = f.description;
                if (rule.descriptionAppend) {
                  newDesc = newDesc ? `${newDesc} ${rule.descriptionAppend}` : rule.descriptionAppend;
                }
                return {
                  ...f,
                  description: newDesc,
                  status: rule.statusOverride || f.status,
                  relevanceState: rule.relevanceState || f.relevanceState,
                  currentRelevance: rule.currentRelevance || f.currentRelevance
                };
              }
              return f;
            });
          }

          if (memoryUpdates.locationUpdates && memoryUpdates.locationUpdates.length > 0) {
            nextMemory.locations = (nextMemory.locations || []).map(l => {
              const rule = memoryUpdates.locationUpdates.find((u: any) => u.name?.toLowerCase() === l.name?.toLowerCase());
              if (rule) {
                let newDesc = l.description;
                if (rule.descriptionAppend) {
                  newDesc = newDesc ? `${newDesc} ${rule.descriptionAppend}` : rule.descriptionAppend;
                }
                const safetyChanged = rule.safetyLevelOverride && rule.safetyLevelOverride !== l.safetyLevel;
                const evolutionReady = safetyChanged || l.evolutionReady || false;
                const evolutionReason = safetyChanged ? "Atmosphere/Safety Shift" : l.evolutionReason;
                return {
                  ...l,
                  description: newDesc,
                  safetyLevel: rule.safetyLevelOverride || l.safetyLevel,
                  relevanceState: rule.relevanceState || l.relevanceState,
                  currentRelevance: rule.currentRelevance || l.currentRelevance,
                  evolutionReady,
                  evolutionReason,
                  availableVisualUpdate: evolutionReady
                };
              }
              return l;
            });
          }

          if (memoryUpdates.artifactUpdates && memoryUpdates.artifactUpdates.length > 0) {
            nextMemory.artifacts = (nextMemory.artifacts || []).map(a => {
              const rule = memoryUpdates.artifactUpdates.find((u: any) => u.name?.toLowerCase() === a.name?.toLowerCase());
              if (rule) {
                let newDesc = a.description;
                if (rule.descriptionAppend) {
                  newDesc = newDesc ? `${newDesc} ${rule.descriptionAppend}` : rule.descriptionAppend;
                }
                const ownerChanged = rule.newOwner && rule.newOwner !== a.currentOwner;
                const evolutionReady = ownerChanged || a.evolutionReady || false;
                const evolutionReason = ownerChanged ? "New Artifact Master" : a.evolutionReason;
                return {
                  ...a,
                  description: newDesc,
                  currentOwner: rule.newOwner || a.currentOwner,
                  relevanceState: rule.relevanceState || a.relevanceState,
                  currentRelevance: rule.currentRelevance || a.currentRelevance,
                  evolutionReady,
                  evolutionReason,
                  availableVisualUpdate: evolutionReady
                };
              }
              return a;
            });
          }

          if (memoryUpdates.newUnresolvedPlotThreads && memoryUpdates.newUnresolvedPlotThreads.length > 0) {
            const currentThreads = nextMemory.unresolvedPlotThreads || [];
            const threads = memoryUpdates.newUnresolvedPlotThreads.filter((t: string) => !currentThreads.some(ct => (typeof ct === 'string' ? ct : ct.description) === t));
            nextMemory.unresolvedPlotThreads = [...currentThreads, ...threads];
          }

          if (memoryUpdates.resolvedPlotThreads && memoryUpdates.resolvedPlotThreads.length > 0) {
            const currentUnresolved = nextMemory.unresolvedPlotThreads || [];
            const currentResolved = nextMemory.resolvedPlotThreads || [];
            let updatedUnresolved = [...currentUnresolved];
            let updatedResolved = [...currentResolved];

            memoryUpdates.resolvedPlotThreads.forEach((title: string) => {
              updatedUnresolved = updatedUnresolved.filter(t => (typeof t === 'string' ? t : t.description).toLowerCase() !== title.toLowerCase());
              if (!updatedResolved.some(r => (typeof r === 'string' ? r : r.description) === title)) {
                updatedResolved = [...updatedResolved, title];
              }
            });

            nextMemory.unresolvedPlotThreads = updatedUnresolved;
            nextMemory.resolvedPlotThreads = updatedResolved;
          }

          if (memoryUpdates.newFactions && memoryUpdates.newFactions.length > 0) {
            const currentFactions = nextMemory.factions || [];
            const added = memoryUpdates.newFactions.map((f: any) => ({
              id: `fct-${Math.random().toString(36).substr(2, 9)}`,
              name: f.name,
              description: f.description || '',
              alignment: f.alignment || 'Neutral',
              headquarters: f.headquarters || '',
              status: f.status || 'Active',
              relevanceState: f.relevanceState || 'active',
              currentRelevance: f.currentRelevance || undefined,
              firstAppeared: chapterNumber
            }));
            const filteredAdded = added.filter((af: any) => !currentFactions.some((cf: any) => cf.name?.toLowerCase() === af.name?.toLowerCase()));
            nextMemory.factions = [...currentFactions, ...filteredAdded];
          }

          if (memoryUpdates.newLocations && memoryUpdates.newLocations.length > 0) {
            const currentLocations = nextMemory.locations || [];
            const added = memoryUpdates.newLocations.map((l: any) => ({
              id: `loc-${Math.random().toString(36).substr(2, 9)}`,
              name: l.name,
              description: l.description || '',
              realm: l.realm || '',
              safetyLevel: l.safetyLevel || 'Safe',
              relevanceState: l.relevanceState || 'active',
              currentRelevance: l.currentRelevance || undefined,
              firstAppeared: chapterNumber
            }));
            const filteredAdded = added.filter((al: any) => !currentLocations.some((cl: any) => cl.name?.toLowerCase() === al.name?.toLowerCase()));
            nextMemory.locations = [...currentLocations, ...filteredAdded];
          }

          if (memoryUpdates.newArtifacts && memoryUpdates.newArtifacts.length > 0) {
            const currentArtifacts = nextMemory.artifacts || [];
            const added = memoryUpdates.newArtifacts.map((a: any) => ({
              id: `art-${Math.random().toString(36).substr(2, 9)}`,
              name: a.name,
              description: a.description || '',
              tier: a.tier || 'Mortal',
              currentOwner: a.currentOwner || 'Unknown',
              relevanceState: a.relevanceState || 'active',
              currentRelevance: a.currentRelevance || undefined,
              firstAppeared: chapterNumber
            }));
            const filteredAdded = added.filter((aa: any) => !currentArtifacts.some((ca: any) => ca.name?.toLowerCase() === aa.name?.toLowerCase()));
            nextMemory.artifacts = [...currentArtifacts, ...filteredAdded];
          }

          if (memoryUpdates.newMCAbilities && memoryUpdates.newMCAbilities.length > 0) {
            const currentAbilities = nextMemory.abilities || [];
            const filteredAbilities = memoryUpdates.newMCAbilities.filter((ab: string) => !currentAbilities.includes(ab));
            nextMemory.abilities = [...currentAbilities, ...filteredAbilities];
          }

          if (memoryUpdates.relationshipUpdates && memoryUpdates.relationshipUpdates.length > 0) {
            const currentRelationships = cloned.relationships || [];
            let updatedRelationships = [...currentRelationships];
            
            memoryUpdates.relationshipUpdates.forEach((relUpdate: any) => {
              if (!relUpdate.sourceName || !relUpdate.targetName) return;

              const existingIndex = updatedRelationships.findIndex(r => 
                r.sourceCharName.toLowerCase() === relUpdate.sourceName.toLowerCase() && 
                r.targetCharName.toLowerCase() === relUpdate.targetName.toLowerCase()
              );
              
              const affinityDelta = Number(relUpdate.affinityDelta) || 0;
              const threatDelta = Number(relUpdate.threatDelta) || 0;

              if (existingIndex >= 0) {
                const existing = updatedRelationships[existingIndex];
                updatedRelationships[existingIndex] = {
                  ...existing,
                  affinity: Math.max(-100, Math.min(100, existing.affinity + affinityDelta)),
                  threat: Math.max(-100, Math.min(100, (existing.threat || 0) + threatDelta)),
                  description: relUpdate.reason || existing.description,
                  updatedAt: new Date().toISOString()
                };
              } else {
                updatedRelationships.push({
                   id: `rel-${Math.random().toString(36).substr(2, 9)}`,
                   sourceCharId: 'unknown',
                   sourceCharName: relUpdate.sourceName,
                   targetCharId: 'unknown',
                   targetCharName: relUpdate.targetName,
                   affinity: Math.max(-100, Math.min(100, affinityDelta)),
                   threat: Math.max(-100, Math.min(100, threatDelta)),
                   description: relUpdate.reason || '',
                   updatedAt: new Date().toISOString()
                });
              }
            });
            cloned.relationships = updatedRelationships;
          }

          const linterWarnings = runMemoryLinter(cloned.memory, nextMemory, data.chapterText);
          if (linterWarnings.length > 0) {
            nextMemory.memoryWarnings = [...(nextMemory.memoryWarnings || []), ...linterWarnings];
          }

          cloned.memory = nextMemory;
        }

        cloned.updatedAt = new Date().toISOString();
        return cloned;
      });

      await store.saveStories(updatedStories);
      awardQi('chapter_generated');

    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Celestial feedback received. Chapter generation failed.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setStreamingChapter(null);
      store.setActiveAgentId(null);
    }
  };

  const handleSteerArc = async (direction: string, customPrompt: string) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    store.setGenerationPhase('steer');
    store.setIsGenerating(true);
    store.setAppError(null);

    const totalPreviousChapters = activeStory.arcs.reduce((acc, arc) => acc + arc.chapters.length, 0);
    const queryIntent = `Overall Arc Direction: ${direction}. Extra Context: ${customPrompt || ''}`;
    const nextChapterNumber = totalPreviousChapters + 1;
    
    try {
      store.setActiveAgentId('scout');
      const apiHeaders = await getApiHeaders();

      const pastSummaries = await retrieveRelevantContext(
        queryIntent,
        nextChapterNumber,
        activeStory,
        apiHeaders,
        10 
      );

      store.setActiveAgentId('versa');
      const response = await fetch('/api/steer-arc', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({
          mcName: activeStory.mcName,
          genre: activeStory.genre,
          customPremise: activeStory.customPremise,
          memory: activeStory.memory,
          pastSummaries,
          currentArcCount: totalPreviousChapters,
          steerDirection: direction,
          userCustomDirections: customPrompt,
          routingConfig: store.routingConfig.storyMaker
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Story steering broke with status: ${response.status}`);
      }

      const data = await response.json();

      const nextChapters: Chapter[] = data.chapters.map((ch: any) => ({
        number: ch.number,
        title: ch.title,
        premise: ch.premise,
        status: 'unread'
      }));

      const newArc: StoryArc = {
        title: data.title || `Volume ${activeStory.arcs.length + 1}`,
        chapters: nextChapters,
        isCompleted: false
      };

      const freshStories = await storyStorage.getStories();
      const updatedStories = freshStories.map(s => {
        if (s.id !== activeStory.id) return s;

        const nextStoriesMemory = { ...s.memory };

        if (data.newCharacters && data.newCharacters.length > 0) {
          const verified = data.newCharacters.map((c: any) => ({
            id: `char-${Math.random().toString(36).substr(2, 9)}`,
            ...c,
            status: c.status || 'alive'
          }));
          nextStoriesMemory.characters = [...nextStoriesMemory.characters, ...verified];
        }

        if (data.newUnresolvedPlotThreads && data.newUnresolvedPlotThreads.length > 0) {
          nextStoriesMemory.unresolvedPlotThreads = [...nextStoriesMemory.unresolvedPlotThreads, ...data.newUnresolvedPlotThreads];
        }

        return {
          ...s,
          arcs: [...s.arcs, newArc],
          memory: nextStoriesMemory,
          updatedAt: new Date().toISOString()
        };
      });

      await store.saveStories(updatedStories);
      store.setSelectedChapterNum(nextChapters[0].number);
    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Failed to steer next story arc successfully.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setActiveAgentId(null);
    }
  };

  const handleAlterFate = async (chapterNumber: number, direction: string, customPrompt: string) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    
    const clonedArcsRaw = await Promise.all(activeStory.arcs.map(async arc => {
      const slicedChapters = arc.chapters.filter(ch => ch.number <= chapterNumber);
      const hydratedChapters = await Promise.all(slicedChapters.map(async ch => {
        if (ch.hasContent || ch.generatedContent) {
          const content = await storyStorage.getChapterContent(activeStory.id, ch.number);
          if (content) {
            return {
              ...ch,
              generatedContent: content.generatedContent,
              blocks: content.blocks,
              summary: content.summary,
              statsChangeMessage: content.statsChangeMessage,
              cuePayload: content.cuePayload,
              _isNewContent: true
            };
          }
        }
        return ch;
      }));
      return { ...arc, chapters: hydratedChapters };
    }));
    
    const clonedArcs = clonedArcsRaw.filter(arc => arc.chapters.length > 0);

    const clonedBookmarks = (activeStory.bookmarks || []).filter(b => b.chapterNumber <= chapterNumber);

    const newStoryId = `story-${Date.now()}-fork`;
    const newStory: StoryWorld = {
      ...activeStory,
      id: newStoryId,
      parentStoryId: activeStory.id,
      forkChapterNumber: chapterNumber,
      title: `[Fate Fork] ${activeStory.title}`,
      arcs: clonedArcs,
      bookmarks: clonedBookmarks,
      updatedAt: new Date().toISOString()
    };

    const updated = [newStory, ...store.stories];
    await store.saveStories(updated);
    store.setActiveStoryId(newStory.id);
    
    store.setGenerationPhase('steer');
    store.setIsGenerating(true);
    store.setAppError(null);

    const totalPreviousChapters = clonedArcs.reduce((acc, arc) => acc + arc.chapters.length, 0);
    const queryIntent = `Overall Arc Direction: ${direction}. Extra Context: ${customPrompt || ''}`;
    const nextChapterNumber = totalPreviousChapters + 1;
    
    try {
      store.setActiveAgentId('scout');
      const apiHeaders = await getApiHeaders();

      const pastSummaries = await retrieveRelevantContext(
        queryIntent,
        nextChapterNumber,
        newStory,
        apiHeaders,
        10 
      );

      store.setActiveAgentId('versa');
      const response = await fetch('/api/steer-arc', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({
          mcName: newStory.mcName,
          genre: newStory.genre,
          customPremise: newStory.customPremise,
          memory: newStory.memory,
          pastSummaries,
          currentArcCount: clonedArcs.length,
          steerDirection: direction,
          userCustomDirections: customPrompt,
          routingConfig: store.routingConfig.storyMaker
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Story fork broke with status: ${response.status}`);
      }

      const data = await response.json();

      const nextChapters: Chapter[] = data.chapters.map((ch: any) => ({
        number: ch.number,
        title: ch.title,
        premise: ch.premise,
        status: 'unread'
      }));

      const newArc: StoryArc = {
        title: data.title || `Vivergence Path`,
        chapters: nextChapters,
        isCompleted: false
      };

      const freshStories = await storyStorage.getStories();
      const updatedStories = freshStories.map((s: any) => {
        if (s.id !== newStory.id) return s;

        const nextStoriesMemory = { ...s.memory };

        if (data.newCharacters && data.newCharacters.length > 0) {
          const verified = data.newCharacters.map((c: any) => ({
            id: `char-${Math.random().toString(36).substr(2, 9)}`,
            ...c,
            status: c.status || 'alive'
          }));
          nextStoriesMemory.characters = [...nextStoriesMemory.characters, ...verified];
        }

        if (data.newUnresolvedPlotThreads && data.newUnresolvedPlotThreads.length > 0) {
          nextStoriesMemory.unresolvedPlotThreads = [...nextStoriesMemory.unresolvedPlotThreads, ...data.newUnresolvedPlotThreads];
        }

        return {
          ...s,
          arcs: [...s.arcs, newArc],
          memory: nextStoriesMemory,
          updatedAt: new Date().toISOString()
        };
      });

      await store.saveStories(updatedStories);
      store.setSelectedChapterNum(nextChapters[0].number);
      awardQi('branch_created');
    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Failed to alter fate successfully.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setActiveAgentId(null);
    }
  };

  const handleUpdateMemoryManual = async (updatedMemory: StoryMemory) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    const updated = store.stories.map(s => {
      if (s.id === activeStory.id) {
        return {
          ...s,
          memory: updatedMemory,
          updatedAt: new Date().toISOString()
        };
      }
      return s;
    });
    await store.saveStories(updated);
  };

  const handleUpdateStoryDirect = async (updatedStory: StoryWorld) => {
    const updated = store.stories.map(s => s.id === updatedStory.id ? updatedStory : s);
    await store.saveStories(updated);
  };

  const handleToggleRead = async (charNum: number) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    const updated = store.stories.map(s => {
      if (s.id === activeStory.id) {
        return {
          ...s,
          arcs: s.arcs.map(arc => ({
            ...arc,
            chapters: arc.chapters.map(ch => {
              if (ch.number === charNum) {
                const newStatus = ch.status === 'read' ? 'unread' : 'read';
                if (newStatus === 'read') awardQi('chapter_finished');
                return {
                  ...ch,
                  status: newStatus as 'unread' | 'read'
                };
              }
              return ch;
            })
          })),
          updatedAt: new Date().toISOString()
        };
      }
      return s;
    });
    await store.saveStories(updated);
  };

  const handleGenerateCover = async (): Promise<{ imageUrls: string[], promptUsed: string } | undefined> => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return undefined;
    store.setGenerationPhase('cover');
    store.setIsGenerating(true);
    store.setAppError(null);
    try {
      const apiHeaders = await getApiHeaders();
      const styleConfig = activeStory.blueprint?.styleBible || "Chinese light novel world aesthetic, xianxia / wuxia fantasy illustration, cinematic, mystical, premium webnovel art.";
      const mcProfile = activeStory.blueprint?.mcProfile || activeStory.mcName;
      const worldOverview = activeStory.blueprint?.worldOverview || activeStory.genre;
      const firstArcPromise = activeStory.blueprint?.firstArcPromise || activeStory.customPremise;

      const prompt = `Cover image for a story titled "${activeStory.title}". Genre: ${activeStory.genre}. Core Premise: ${activeStory.customPremise}. Main character visual description: ${mcProfile}. Main visual conflict: ${firstArcPromise}. World aesthetic: ${worldOverview}. Shared visual style: ${styleConfig}. Epic fantasy webnovel book cover, digital painting, textless.`;

      const response = await fetch('/api/generate-card-image', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({ prompt, type: "cover", routingConfig: store.routingConfig.imageGenerator })
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Failed to generate cover art.");

      let newImageUrls = data.imageUrls;
      if (!newImageUrls && data.imageUrl) newImageUrls = [data.imageUrl];
      if (!newImageUrls && data.fallbackUrl) newImageUrls = [data.fallbackUrl];

      if (newImageUrls && newImageUrls.length > 0) {
        return { imageUrls: newImageUrls, promptUsed: prompt };
      }
    } catch(err: any) {
      store.setAppError(err.message || "Failed to forge new cover.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
    }
    return undefined;
  };

  const handleApplyCover = async (imageUrl: string, promptUsed: string) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;

    const imageRecord: GeneratedImage = {
      id: Math.random().toString(36).substring(2, 10),
      entityId: activeStory.id,
      entityType: 'cover',
      imageUrl,
      promptUsed,
      createdAt: new Date().toISOString(),
      isCurrent: true,
      chapterNumber: activeStory.currentChapterNumber
    };
    
    const currentHistory = activeStory.imageHistory || [];
    const updatedHistory: GeneratedImage[] = currentHistory.map(img => 
      img.entityType === 'cover' ? { ...img, isCurrent: false } : img
    ).concat(imageRecord);

    handleUpdateStoryDirect({ 
      ...activeStory, 
      imageUrl,
      imageHistory: updatedHistory,
      evolutionReady: false,
      availableVisualUpdate: false,
      lastImageChapter: activeStory.currentChapterNumber
    });
  };

  const handleSealChapter = async (chapterNumber: number) => {
    const activeStory = store.stories.find((s) => s.id === store.activeStoryId);
    if (!activeStory) return;

    const generateContentHash = async (content: string): Promise<string> => {
      try {
        const encoder = new TextEncoder();
        const data = encoder.encode(content || '');
        const hashBuffer = await window.crypto.subtle.digest('SHA-256', data);
        const hashArray = Array.from(new Uint8Array(hashBuffer));
        return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
      } catch (err) {
        return Math.random().toString(36).substring(2, 15);
      }
    };

    const newArcs = await Promise.all(activeStory.arcs.map(async (arc) => {
      const newChapters = await Promise.all(arc.chapters.map(async (ch) => {
        if (ch.number === chapterNumber) {
          const contentHash = await generateContentHash(ch.generatedContent || '');
          const versionId = crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2, 15);
          const branchAnchor = crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2, 15);
          
          return { 
            ...ch, 
            isSealed: true,
            contentHash,
            sealedAt: Date.now(),
            versionId,
            assetManifest: {},
            translationCache: {},
            audioCueCache: {},
            branchAnchor
          };
        }
        return ch;
      }));
      return { ...arc, chapters: newChapters };
    }));

    await handleUpdateStoryDirect({ ...activeStory, arcs: newArcs });
    awardQi('chapter_sealed');
  };

  return {
    handleGenerateBlueprint,
    handleStartStory,
    handleGenerateChapter,
    handleSteerArc,
    handleAlterFate,
    handleSealChapter,
    handleUpdateMemoryManual,
    handleUpdateStoryDirect,
    handleToggleRead,
    handleGenerateCover,
    handleApplyCover
  };
};
