import { useAppStore } from '../store/useAppStore';
import { secureStorage } from '../lib/encryption';
import { retrieveRelevantContext, generateEmbedding } from '../lib/rag';
import { Story, IntakeData, WorldBlueprint, Chapter, StoryArc, StoryMemory, StoryWorld } from '../types';
import { storyStorage } from '../lib/storage';

const extractJsonBlocks = (rawStr: string): any[] => {
  // 1. Try arrays wrapped in markdown or raw
  try {
    const arrayMatch = rawStr.match(/\[\s*\{[\s\S]*\}\s*\]/);
    if (arrayMatch) {
       const parsed = JSON.parse(arrayMatch[0]);
       if (Array.isArray(parsed) && parsed.length > 0 && (typeof parsed[0].text === 'string' || typeof parsed[0].content === 'string')) {
          return parsed.map(b => ({ ...b, text: b.text || b.content }));
       }
    }
  } catch(e) {}

  // 2. Strict NDJSON line-by-line fallback
  let blocks: any[] = [];
  const lines = rawStr.split('\n');
  for (let l of lines) {
    const trimmed = l.trim();
    if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
      try {
        const obj = JSON.parse(trimmed);
        if (obj && (typeof obj.text === 'string' || typeof obj.content === 'string')) {
          blocks.push({ ...obj, text: obj.text || obj.content });
        }
      } catch (e) {}
    }
  }
  if (blocks.length > 0) return blocks;

  // 3. Balanced brace extraction (Handles pretty-printed, drift, trailing commas gracefully-ish but JSON.parse must succeed)
  let braceBlocks: any[] = [];
  let depth = 0;
  let currentBlock = "";
  let inString = false;
  let escapeNext = false;
  
  for (let i = 0; i < rawStr.length; i++) {
    const char = rawStr[i];
    if (escapeNext) {
      if (depth > 0) currentBlock += char;
      escapeNext = false;
      continue;
    }
    if (char === '\\') {
      escapeNext = true;
      if (depth > 0) currentBlock += char;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      if (depth > 0) currentBlock += char;
      continue;
    }
    if (!inString) {
      if (char === '{') {
        if (depth === 0) currentBlock = '{';
        else currentBlock += char;
        depth++;
      } else if (char === '}') {
        depth--;
        currentBlock += char;
        if (depth === 0) {
          try {
            // Fix trailing commas often generated by LLMs before parsing
            let fixStr = currentBlock.replace(/,\s*([\]}])/g, '$1');
            const obj = JSON.parse(fixStr);
            if (obj && (typeof obj.text === 'string' || typeof obj.content === 'string')) {
              braceBlocks.push({ ...obj, text: obj.text || obj.content });
            }
          } catch(e) {}
        }
      } else if (depth > 0) {
         currentBlock += char;
      }
    } else {
      if (depth > 0) currentBlock += char;
    }
  }
  return braceBlocks;
};

const extractJsonMeta = (rawStr: string): any => {
  let cleanJson = rawStr.replace(/```json/gi, '').replace(/```/g, '').trim();
  cleanJson = cleanJson.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  
  try { return JSON.parse(cleanJson); } catch (e) {}

  // Find longest balanced object
  let depth = 0;
  let currentBlock = "";
  let inString = false;
  let escapeNext = false;
  let longestObject: any = null;
  let longestLength = 0;
  
  for (let i = 0; i < cleanJson.length; i++) {
    const char = cleanJson[i];
    if (escapeNext) {
      if (depth > 0) currentBlock += char;
      escapeNext = false;
      continue;
    }
    if (char === '\\') {
      escapeNext = true;
      if (depth > 0) currentBlock += char;
      continue;
    }
    if (char === '"') {
      inString = !inString;
      if (depth > 0) currentBlock += char;
      continue;
    }
    if (!inString) {
      if (char === '{') {
        if (depth === 0) currentBlock = '{';
        else currentBlock += char;
        depth++;
      } else if (char === '}') {
        depth--;
        currentBlock += char;
        if (depth === 0) {
          try {
            let fixStr = currentBlock.replace(/,\s*([\]}])/g, '$1');
            const obj = JSON.parse(fixStr);
            if (currentBlock.length > longestLength) {
              longestLength = currentBlock.length;
              longestObject = obj;
            }
          } catch(e) {}
        }
      } else if (depth > 0) {
         currentBlock += char;
      }
    } else {
      if (depth > 0) currentBlock += char;
    }
  }
  
  return longestObject || {};
};

export const useStoryEngine = () => {
  const store = useAppStore();

  const getApiHeaders = () => {
    const apiHeaders: Record<string, string> = { 'Content-Type': 'application/json' };
    const gemini = secureStorage.getItem('@seihouse/api-key-gemini');
    const openrouter = secureStorage.getItem('@seihouse/api-key-openrouter');
    const ollama = secureStorage.getItem('@seihouse/api-key-ollama-host');
    if (gemini) apiHeaders['x-gemini-key'] = gemini;
    if (openrouter) apiHeaders['x-openrouter-key'] = openrouter;
    if (ollama) apiHeaders['x-ollama-host'] = ollama;
    return apiHeaders;
  };

  const handleGenerateBlueprint = async (intake: IntakeData): Promise<WorldBlueprint> => {
    store.setGenerationPhase('blueprint');
    store.setActiveAgentId('versa');
    store.setIsGenerating(true);
    store.setAppError(null);
    try {
      const apiHeaders = getApiHeaders();
      const response = await fetch('/api/generate-blueprint', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({ intake, routingConfig: store.routingConfig.storyMaker })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Blueprint generation failed: ${response.status}`);
      }
      return await response.json();
    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Failed to generate world blueprint.");
      throw err;
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setActiveAgentId(null);
    }
  };

  const handleStartStory = async (intake: IntakeData, blueprint: WorldBlueprint, chapterCount: number) => {
    store.setGenerationPhase('initial-arc');
    store.setActiveAgentId('versa');
    store.setIsGenerating(true);
    store.setAppError(null);

    try {
      const apiHeaders = getApiHeaders();
      const response = await fetch('/api/generate-initial-arc', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({ intake, blueprint, chapterCount, routingConfig: store.routingConfig.storyMaker })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Server bounds ruptured with status: ${response.status}`);
      }

      const responseData = await response.json();

      const formattedChapters: Chapter[] = responseData.chapters.map((ch: any) => ({
        number: ch.number,
        title: ch.title,
        premise: ch.premise,
        status: 'unread'
      }));

      const newStory: Story = {
        id: `story-${Date.now()}`,
        title: responseData.title || blueprint.title || 'The Ascension Chronicles',
        genre: intake.genrePath || 'Xianxia',
        mcName: intake.mcName || 'Unknown',
        customPremise: intake.corePremise || blueprint.logline || '',
        intake: intake,
        blueprint: blueprint,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        currentChapterNumber: 1,
        memory: {
          powerSystem: responseData.powerSystem || blueprint.powerSystemOutline,
          currentPowerStage: responseData.currentPowerStage || 'Novice stage',
          worldRules: responseData.worldRules || ['Survival of the fittest'],
          characters: responseData.characters?.map((c: any) => ({
            id: `char-${Math.random().toString(36).substr(2, 9)}`,
            ...c
          })) || [],
          unresolvedPlotThreads: responseData.unresolvedPlotThreads || [],
          resolvedPlotThreads: []
        },
        arcs: [
          {
            title: responseData.title || 'Volume I Genesis',
            chapters: formattedChapters,
            isCompleted: false
          }
        ]
      };

      const updated = [newStory, ...store.stories];
      await store.saveStories(updated);
      store.setActiveStoryId(newStory.id);
      store.setSelectedChapterNum(1);
      store.setCurrentScreen('detail');
    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Failed to align celestial gates.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setActiveAgentId(null);
    }
  };

  const handleGenerateChapter = async (chapterNumber: number) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    store.setGenerationPhase('chapter');
    store.setIsGenerating(true);
    store.setAppError(null);

    const selectedArcIndex = activeStory.arcs.findIndex(arc => arc.chapters.some(c => c.number === chapterNumber));
    if (selectedArcIndex === -1) return;

    const currentArc = activeStory.arcs[selectedArcIndex];
    const targetChapter = currentArc.chapters.find(c => c.number === chapterNumber);
    if (!targetChapter) return;

    try {
      store.setActiveAgentId('scout');
      const apiHeaders = getApiHeaders();

      const pastSummaries = await retrieveRelevantContext(
        targetChapter.premise || activeStory.customPremise,
        chapterNumber,
        activeStory,
        apiHeaders,
        5
      );

      store.setActiveAgentId('versa');
      const response = await fetch('/api/generate-chapter-stream', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({
          mcName: activeStory.mcName,
          genre: activeStory.genre,
          customPremise: activeStory.customPremise,
          memory: activeStory.memory,
          pastSummaries,
          currentChapter: {
            number: targetChapter.number,
            title: targetChapter.title,
            premise: targetChapter.premise
          },
          routingConfig: store.routingConfig.storyMaker
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Meridian clash in chapter generation. Status: ${response.status}`);
      }

      if (!response.body) throw new Error("No streaming body available.");

      const reader = response.body.getReader();
      const decoder = new TextDecoder("utf-8");
      let accumulatedRaw = "";
      let buffer = "";

      const textHeader = "---CHAPTER_BLOCKS---";
      const jsonHeader = "---JSON_META---";

      while(true) {
        const { value, done } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        
        let lines = buffer.split('\\n');
        buffer = lines.pop() || "";
        
        for (const line of lines) {
          if (line.startsWith('data: ') && line !== 'data: [DONE]') {
            try {
              const parsed = JSON.parse(line.substring(6));
              if (parsed.error) throw new Error(parsed.error);
              if (parsed.chunk) {
                accumulatedRaw += parsed.chunk;
                
                let currentChapterText = "";
                let blocksData: any[] = [];
                let rawBlocksStr = accumulatedRaw;

                if (accumulatedRaw.includes(textHeader)) {
                  const startIndex = accumulatedRaw.indexOf(textHeader) + textHeader.length;
                  if (accumulatedRaw.includes(jsonHeader)) {
                    rawBlocksStr = accumulatedRaw.substring(startIndex, accumulatedRaw.indexOf(jsonHeader)).trim();
                  } else {
                    rawBlocksStr = accumulatedRaw.substring(startIndex).trim();
                  }
                } else if (accumulatedRaw.includes(jsonHeader)) {
                  rawBlocksStr = accumulatedRaw.substring(0, accumulatedRaw.indexOf(jsonHeader)).trim();
                }

                blocksData = extractJsonBlocks(rawBlocksStr);
                
                if (blocksData.length > 0) {
                   currentChapterText = blocksData.map(b => b.text).join('\\n\\n');
                } else {
                   currentChapterText = rawBlocksStr.replace(/\`\`\`json/gi, '').replace(/\`\`\`/g, '').trim();
                }

                if (!currentChapterText) {
                   currentChapterText = accumulatedRaw;
                }

                store.setStreamingChapter({
                  number: chapterNumber,
                  content: currentChapterText || "Condensing celestial aura...",
                  blocks: blocksData.length > 0 ? blocksData : undefined
                });
              }
            } catch (e: any) {
              if (e.message && e.message !== "Unexpected end of JSON input") {
                console.error("Stream parse error:", e);
              }
            }
          }
        }
      }

      let data: any = { chapterText: "", blocks: [], summary: "An ethereal mist obscures the historical records.", statsChangeMessage: "None", memoryUpdates: {} };
      
      let rawBlocksStr = accumulatedRaw;
      let rawMetaStr = "";

      if (accumulatedRaw.includes(textHeader)) {
        const startIndex = accumulatedRaw.indexOf(textHeader) + textHeader.length;
        if (accumulatedRaw.includes(jsonHeader)) {
          rawBlocksStr = accumulatedRaw.substring(startIndex, accumulatedRaw.indexOf(jsonHeader)).trim();
          rawMetaStr = accumulatedRaw.substring(accumulatedRaw.indexOf(jsonHeader) + jsonHeader.length).trim();
        } else {
          rawBlocksStr = accumulatedRaw.substring(startIndex).trim();
        }
      } else if (accumulatedRaw.includes(jsonHeader)) {
        rawBlocksStr = accumulatedRaw.substring(0, accumulatedRaw.indexOf(jsonHeader)).trim();
        rawMetaStr = accumulatedRaw.substring(accumulatedRaw.indexOf(jsonHeader) + jsonHeader.length).trim();
      }

      const parsedMeta = rawMetaStr ? extractJsonMeta(rawMetaStr) : extractJsonMeta(accumulatedRaw);
      const parsedBlocks = extractJsonBlocks(rawBlocksStr);

      data = { ...data, ...parsedMeta };
      data.blocks = parsedBlocks;
      
      if (parsedBlocks.length > 0) {
        data.chapterText = parsedBlocks.map((b: any) => b.text).join('\\n\\n');
      } else {
        data.chapterText = rawBlocksStr.replace(/\`\`\`json/gi, '').replace(/\`\`\`/g, '').trim();
        // If meta was parsed from accumulatedRaw due to missing header, it might pollute chapterText
        // but text is generally fine unless it's very messy. 
      }
      
      if (!data.chapterText) {
        data.chapterText = accumulatedRaw;
      }

      let newChapterEmbedding;
      if (data.summary) {
        newChapterEmbedding = await generateEmbedding(data.summary, apiHeaders);
      }

      const freshStories = await storyStorage.getStories();
      const updatedStories = freshStories.map((s: Story) => {
        if (s.id !== activeStory.id) return s;

        const cloned = { ...s };
        
        cloned.arcs = cloned.arcs.map((arc, aIdx) => {
          if (aIdx !== selectedArcIndex) return arc;
          return {
            ...arc,
            chapters: arc.chapters.map(ch => {
              if (ch.number !== chapterNumber) return ch;
              return {
                ...ch,
                _isNewContent: true,
                generatedContent: data.chapterText,
                blocks: data.blocks,
                summary: data.summary,
                embedding: newChapterEmbedding,
                statsChangeMessage: data.statsChangeMessage !== 'None' ? data.statsChangeMessage : undefined,
                cuePayload: data.cuePayload,
                status: 'read' as const
              };
            })
          };
        });

        const isArcFinished = cloned.arcs[selectedArcIndex].chapters.every(ch => ch.hasContent || !!ch.generatedContent);
        if (isArcFinished) {
          cloned.arcs[selectedArcIndex].isCompleted = true;
        }

        const memoryUpdates = data.memoryUpdates;
        if (memoryUpdates) {
          const nextMemory: StoryMemory = { ...cloned.memory };
          
          if (memoryUpdates.currentPowerStage) {
            nextMemory.currentPowerStage = memoryUpdates.currentPowerStage;
          }

          if (memoryUpdates.newCharacters && memoryUpdates.newCharacters.length > 0) {
            const added = memoryUpdates.newCharacters.map((c: any) => ({
              id: `char-${Math.random().toString(36).substr(2, 9)}`,
              name: c.name,
              role: c.role || 'Neutral figure',
              description: c.description || '',
              relationshipToMC: c.relationshipToMC || 'Neutral',
              status: c.status || 'alive',
              powerLevel: c.powerLevel || undefined,
              abilities: c.abilities || undefined,
              faction: c.faction || undefined
            }));
            nextMemory.characters = [...(nextMemory.characters || []), ...added];
          }

          if (memoryUpdates.characterStatusUpdates && memoryUpdates.characterStatusUpdates.length > 0) {
            nextMemory.characters = (nextMemory.characters || []).map(char => {
              const rule = memoryUpdates.characterStatusUpdates.find((u: any) => u.name?.toLowerCase() === char.name?.toLowerCase());
              if (rule) {
                const nextAbilities = char.abilities || [];
                const mergedAbilities = rule.newAbilities 
                  ? Array.from(new Set([...nextAbilities, ...rule.newAbilities]))
                  : nextAbilities;
                
                let newDesc = char.description;
                if (rule.descriptionAppend) {
                  newDesc = newDesc ? `${newDesc} ${rule.descriptionAppend}` : rule.descriptionAppend;
                }

                return {
                  ...char,
                  description: newDesc,
                  status: rule.newStatus || char.status,
                  relationshipToMC: rule.newRelationship || char.relationshipToMC,
                  powerLevel: rule.newPowerLevel || char.powerLevel,
                  abilities: mergedAbilities.length > 0 ? mergedAbilities : undefined
                };
              }
              return char;
            });
          }

          if (memoryUpdates.factionUpdates && memoryUpdates.factionUpdates.length > 0) {
            nextMemory.factions = (nextMemory.factions || []).map(f => {
              const rule = memoryUpdates.factionUpdates.find((u: any) => u.name?.toLowerCase() === f.name?.toLowerCase());
              if (rule) {
                let newDesc = f.description;
                if (rule.descriptionAppend) {
                  newDesc = newDesc ? `${newDesc} ${rule.descriptionAppend}` : rule.descriptionAppend;
                }
                return {
                  ...f,
                  description: newDesc,
                  status: rule.statusOverride || f.status
                };
              }
              return f;
            });
          }

          if (memoryUpdates.locationUpdates && memoryUpdates.locationUpdates.length > 0) {
            nextMemory.locations = (nextMemory.locations || []).map(l => {
              const rule = memoryUpdates.locationUpdates.find((u: any) => u.name?.toLowerCase() === l.name?.toLowerCase());
              if (rule) {
                let newDesc = l.description;
                if (rule.descriptionAppend) {
                  newDesc = newDesc ? `${newDesc} ${rule.descriptionAppend}` : rule.descriptionAppend;
                }
                return {
                  ...l,
                  description: newDesc,
                  safetyLevel: rule.safetyLevelOverride || l.safetyLevel
                };
              }
              return l;
            });
          }

          if (memoryUpdates.artifactUpdates && memoryUpdates.artifactUpdates.length > 0) {
            nextMemory.artifacts = (nextMemory.artifacts || []).map(a => {
              const rule = memoryUpdates.artifactUpdates.find((u: any) => u.name?.toLowerCase() === a.name?.toLowerCase());
              if (rule) {
                let newDesc = a.description;
                if (rule.descriptionAppend) {
                  newDesc = newDesc ? `${newDesc} ${rule.descriptionAppend}` : rule.descriptionAppend;
                }
                return {
                  ...a,
                  description: newDesc,
                  currentOwner: rule.newOwner || a.currentOwner
                };
              }
              return a;
            });
          }

          if (memoryUpdates.newUnresolvedPlotThreads && memoryUpdates.newUnresolvedPlotThreads.length > 0) {
            const currentThreads = nextMemory.unresolvedPlotThreads || [];
            const threads = memoryUpdates.newUnresolvedPlotThreads.filter((t: string) => !currentThreads.includes(t));
            nextMemory.unresolvedPlotThreads = [...currentThreads, ...threads];
          }

          if (memoryUpdates.resolvedPlotThreads && memoryUpdates.resolvedPlotThreads.length > 0) {
            const currentUnresolved = nextMemory.unresolvedPlotThreads || [];
            const currentResolved = nextMemory.resolvedPlotThreads || [];
            let updatedUnresolved = [...currentUnresolved];
            let updatedResolved = [...currentResolved];

            memoryUpdates.resolvedPlotThreads.forEach((title: string) => {
              updatedUnresolved = updatedUnresolved.filter(t => t.toLowerCase() !== title.toLowerCase());
              if (!updatedResolved.includes(title)) {
                updatedResolved = [...updatedResolved, title];
              }
            });

            nextMemory.unresolvedPlotThreads = updatedUnresolved;
            nextMemory.resolvedPlotThreads = updatedResolved;
          }

          if (memoryUpdates.newFactions && memoryUpdates.newFactions.length > 0) {
            const currentFactions = nextMemory.factions || [];
            const added = memoryUpdates.newFactions.map((f: any) => ({
              id: `fct-${Math.random().toString(36).substr(2, 9)}`,
              name: f.name,
              description: f.description || '',
              alignment: f.alignment || 'Neutral',
              headquarters: f.headquarters || '',
              status: f.status || 'Active'
            }));
            const filteredAdded = added.filter((af: any) => !currentFactions.some((cf: any) => cf.name?.toLowerCase() === af.name?.toLowerCase()));
            nextMemory.factions = [...currentFactions, ...filteredAdded];
          }

          if (memoryUpdates.newLocations && memoryUpdates.newLocations.length > 0) {
            const currentLocations = nextMemory.locations || [];
            const added = memoryUpdates.newLocations.map((l: any) => ({
              id: `loc-${Math.random().toString(36).substr(2, 9)}`,
              name: l.name,
              description: l.description || '',
              realm: l.realm || '',
              safetyLevel: l.safetyLevel || 'Safe'
            }));
            const filteredAdded = added.filter((al: any) => !currentLocations.some((cl: any) => cl.name?.toLowerCase() === al.name?.toLowerCase()));
            nextMemory.locations = [...currentLocations, ...filteredAdded];
          }

          if (memoryUpdates.newArtifacts && memoryUpdates.newArtifacts.length > 0) {
            const currentArtifacts = nextMemory.artifacts || [];
            const added = memoryUpdates.newArtifacts.map((a: any) => ({
              id: `art-${Math.random().toString(36).substr(2, 9)}`,
              name: a.name,
              description: a.description || '',
              tier: a.tier || 'Mortal',
              currentOwner: a.currentOwner || 'Unknown'
            }));
            const filteredAdded = added.filter((aa: any) => !currentArtifacts.some((ca: any) => ca.name?.toLowerCase() === aa.name?.toLowerCase()));
            nextMemory.artifacts = [...currentArtifacts, ...filteredAdded];
          }

          if (memoryUpdates.newMCAbilities && memoryUpdates.newMCAbilities.length > 0) {
            const currentAbilities = nextMemory.abilities || [];
            const filteredAbilities = memoryUpdates.newMCAbilities.filter((ab: string) => !currentAbilities.includes(ab));
            nextMemory.abilities = [...currentAbilities, ...filteredAbilities];
          }

          cloned.memory = nextMemory;
        }

        cloned.updatedAt = new Date().toISOString();
        return cloned;
      });

      await store.saveStories(updatedStories);

    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Celestial feedback received. Chapter generation failed.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setStreamingChapter(null);
      store.setActiveAgentId(null);
    }
  };

  const handleSteerArc = async (direction: string, customPrompt: string) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    store.setGenerationPhase('steer');
    store.setIsGenerating(true);
    store.setAppError(null);

    const totalPreviousChapters = activeStory.arcs.reduce((acc, arc) => acc + arc.chapters.length, 0);
    const queryIntent = `Overall Arc Direction: ${direction}. Extra Context: ${customPrompt || ''}`;
    const nextChapterNumber = totalPreviousChapters + 1;
    
    try {
      store.setActiveAgentId('scout');
      const apiHeaders = getApiHeaders();

      const pastSummaries = await retrieveRelevantContext(
        queryIntent,
        nextChapterNumber,
        activeStory,
        apiHeaders,
        10 
      );

      store.setActiveAgentId('versa');
      const response = await fetch('/api/steer-arc', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({
          mcName: activeStory.mcName,
          genre: activeStory.genre,
          customPremise: activeStory.customPremise,
          memory: activeStory.memory,
          pastSummaries,
          currentArcCount: totalPreviousChapters,
          steerDirection: direction,
          userCustomDirections: customPrompt,
          routingConfig: store.routingConfig.storyMaker
        })
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Story steering broke with status: ${response.status}`);
      }

      const data = await response.json();

      const nextChapters: Chapter[] = data.chapters.map((ch: any) => ({
        number: ch.number,
        title: ch.title,
        premise: ch.premise,
        status: 'unread'
      }));

      const newArc: StoryArc = {
        title: data.title || `Volume ${activeStory.arcs.length + 1}`,
        chapters: nextChapters,
        isCompleted: false
      };

      const freshStories = await storyStorage.getStories();
      const updatedStories = freshStories.map(s => {
        if (s.id !== activeStory.id) return s;

        const nextStoriesMemory = { ...s.memory };

        if (data.newCharacters && data.newCharacters.length > 0) {
          const verified = data.newCharacters.map((c: any) => ({
            id: `char-${Math.random().toString(36).substr(2, 9)}`,
            ...c,
            status: c.status || 'alive'
          }));
          nextStoriesMemory.characters = [...nextStoriesMemory.characters, ...verified];
        }

        if (data.newUnresolvedPlotThreads && data.newUnresolvedPlotThreads.length > 0) {
          nextStoriesMemory.unresolvedPlotThreads = [...nextStoriesMemory.unresolvedPlotThreads, ...data.newUnresolvedPlotThreads];
        }

        return {
          ...s,
          arcs: [...s.arcs, newArc],
          memory: nextStoriesMemory,
          updatedAt: new Date().toISOString()
        };
      });

      await store.saveStories(updatedStories);
      store.setSelectedChapterNum(nextChapters[0].number);
    } catch (err: any) {
      console.error(err);
      store.setAppError(err.message || "Failed to steer next story arc successfully.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
      store.setActiveAgentId(null);
    }
  };

  const handleUpdateMemoryManual = async (updatedMemory: StoryMemory) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    const updated = store.stories.map(s => {
      if (s.id === activeStory.id) {
        return {
          ...s,
          memory: updatedMemory,
          updatedAt: new Date().toISOString()
        };
      }
      return s;
    });
    await store.saveStories(updated);
  };

  const handleUpdateStoryDirect = async (updatedStory: StoryWorld) => {
    const updated = store.stories.map(s => s.id === updatedStory.id ? updatedStory : s);
    await store.saveStories(updated);
  };

  const handleToggleRead = async (charNum: number) => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    const updated = store.stories.map(s => {
      if (s.id === activeStory.id) {
        return {
          ...s,
          arcs: s.arcs.map(arc => ({
            ...arc,
            chapters: arc.chapters.map(ch => {
              if (ch.number === charNum) {
                return {
                  ...ch,
                  status: (ch.status === 'read' ? 'unread' : 'read') as 'unread' | 'read'
                };
              }
              return ch;
            })
          })),
          updatedAt: new Date().toISOString()
        };
      }
      return s;
    });
    await store.saveStories(updated);
  };

  const handleGenerateCover = async () => {
    const activeStory = store.stories.find(s => s.id === store.activeStoryId);
    if (!activeStory) return;
    store.setGenerationPhase('cover');
    store.setIsGenerating(true);
    store.setAppError(null);
    try {
      const apiHeaders = getApiHeaders();
      const prompt = `Epic fantasy webnovel book cover for a story titled "${activeStory.title}", genre: ${activeStory.genre}. Concept: ${activeStory.customPremise}. The cover focuses on the journey of ${activeStory.mcName}. Cinematic lighting, digital painting, majestic, dark fantasy aesthetics, textless.`;

      const response = await fetch('/api/generate-card-image', {
        method: 'POST',
        headers: apiHeaders,
        body: JSON.stringify({ prompt, type: "cover", routingConfig: store.routingConfig.imageGenerator })
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Failed to generate cover art.");

      const newImageUrl = data.imageUrl || data.fallbackUrl;
      if (newImageUrl) {
        handleUpdateStoryDirect({ ...activeStory, imageUrl: newImageUrl } as any);
      }
    } catch(err: any) {
      store.setAppError(err.message || "Failed to forge new cover.");
    } finally {
      store.setIsGenerating(false);
      store.setGenerationPhase(null);
    }
  };

  return {
    handleGenerateBlueprint,
    handleStartStory,
    handleGenerateChapter,
    handleSteerArc,
    handleUpdateMemoryManual,
    handleUpdateStoryDirect,
    handleToggleRead,
    handleGenerateCover
  };
};
